# port, defaults to 80
port: "8080"
# sqite://path/to/db or postgres://database@url, , default to $HOME/.config/tanoshi/tanoshi.db
database_url: sqlite://./tanoshi.db
# url to repository, default to https://faldez.github.io/tanoshi-extensions/
extension_url: https://faldez.github.io/tanoshi-extensions/
# path to local manga directory, default to $HOME/.config/tanoshi/manga
local_dir: C:\Users\faldez/.config/tanoshi/manga