name: release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
     matrix:
      include:
        - os: ubuntu-latest
          arch: amd64
          asset_name: tanoshi-linux-amd64
          standalone: false
        - os: ubuntu-latest
          arch: amd64
          asset_name: tanoshi-desktop-linux-amd64
          standalone: true
        - os: windows-latest
          arch: amd64
          asset_name: tanoshi-windows-amd64.exe
          standalone: false
        - os: windows-latest
          arch: amd64
          asset_name: tanoshi-desktop-windows-amd64.exe
          standalone: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15' # The Go version to download (if necessary) and use.
      - name: Build Frontend
        run: cd web && yarn && yarn build
      - name: Install go deps
        run: |
          go get github.com/GeertJohan/go.rice
          go get github.com/GeertJohan/go.rice/rice
          go get github.com/akavel/rsrc
      - name: Rice embed
        if:  ${{ matrix.os != 'windows-latest' }}
        run: cd $GITHUB_WORKSPACE/cmd/tanoshi && /home/runner/go/bin/rice embed-go
      - name: Rice embed Windows
        if:  ${{ matrix.os == 'windows-latest' }}
        run: cd cmd\tanoshi && rice embed-go
      - name: Install package
        if:  ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt update && sudo apt install -y gtk+-3.0 webkit2gtk-4.0
      - name: Build
        if:  ${{ matrix.standalone == false }}
        run: go build -tags headless -o build/${{ matrix.asset_name }} ./cmd/tanoshi
      - name: Setup MinGW
        if:  ${{ matrix.standalone == true && matrix.os == 'windows-latest' }} 
        uses: egor-tensin/setup-mingw@v2
      - name: rsrc
        if:  ${{ matrix.standalone == true && matrix.os == 'windows-latest' }} 
        run: rsrc -manifest build\windows\tanoshi.exe.manifest -ico assets\tanoshi.ico -o cmd\tanoshi\tanoshi.syso
      - name: Build Desktop Windows
        if:  ${{ matrix.standalone == true && matrix.os == 'windows-latest' }} 
        run: go build -tags desktop -ldflags '-H windowsgui' -o build/${{ matrix.asset_name }} ./cmd/tanoshi
      - name: Build Desktop
        if:  ${{ matrix.standalone == true && matrix.os != 'windows-latest' }} 
        run: go build -tags desktop -o build/${{ matrix.asset_name }} ./cmd/tanoshi
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/${{ matrix.asset_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
    